spring.application.name=url-shortener-sb

spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=5af29e33a8e909421d15a3fe74c02ca83cec07afa6759982dfd0f67a8fcab6cd
jwt.expiration=172800000

